# Generated by Django 2.2 on 2021-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comp_job_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
