# Generated by Django 2.2 on 2021-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_stu_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='岗位名称')),
                ('work_demand', models.CharField(max_length=80, null=True, verbose_name='能力要求')),
                ('company_locale', models.CharField(max_length=20, null=True, verbose_name='地点')),
                ('company_name', models.CharField(max_length=40, null=True, verbose_name='公司名')),
                ('guimo', models.CharField(max_length=20, null=True, verbose_name='公司规模')),
                ('job_salary', models.CharField(max_length=20, null=True, verbose_name='公司薪资')),
                ('job_salary_fif', models.BooleanField(choices=[(True, '是'), (False, '否')], null=True, verbose_name='薪资是否不超过15K')),
                ('demand', models.CharField(max_length=20, null=True, verbose_name='demand')),
            ],
            options={
                'verbose_name_plural': '招聘岗位信息表',
            },
        ),
    ]
