# Generated by Django 2.2 on 2021-06-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_name',
        ),
    ]
