# Generated by Django 2.2 on 2021-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210602_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100, null=True, verbose_name='公司名'),
        ),
    ]
