# Generated by Django 2.2 on 2021-06-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210604_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='password',
            field=models.CharField(max_length=20, null=True, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='stu',
            name='stuid',
            field=models.CharField(max_length=20, verbose_name='学号（登录账号）'),
        ),
    ]
